name: Docker image release

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master      
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: troeger/culturestreams
        tags: latest
  release:
    runs-on: self-hosted
    steps:
    - name: Install Kubectl
      run: sudo apt install -y kubectl
    - name: Restart pod for the web app
      run: kubectl -n troeger delete pod -l app=culturestreams
